#!/bin/sh

TEMP=`getopt -o hcd:r: --long help,create-config,directory-name:,name-regex: -n 'cr.sh' -- "$@"`

eval set -- "$TEMP"

while true; do
  case "$1" in
    -h | --help ) help; break ;;
    -c | --create-config ) CREATE_CONFIG=true; shift ;;
    -d | --directory-name ) DIR_NAME=$2; [ ! -d "$DIR_NAME" ] && mkdir $DIR_NAME; shift 2 ;;
    -r | --name-regex ) REGEX="$2"; ZONE="devcluster.openshift.com."; shift 2 ;;
    -- ) shift; break ;;
    * ) break ;;
  esac
done

help () {
	echo "Using https://github.com/matejvasek/delete-routes"
	echo "-h, --help: print help"
	echo "-c, --create-config: creates a install-config.yaml"
	echo "-d, --directory-name: directory, where to create a cluster"
	echo "-r, --name-regex: DNS entires in route 53 that satisfy given regex will be deleted"
}

if [ -z "$REGEX" ]
then
	echo "--name-regex is not specified, initial check for existing domain name will not take place"
else
	delete-routes -name-regex "$REGEX" -zone "$ZONE"
fi


openshift-install create cluster --dir=$DIR_NAME

[ "$CREATE_CONFIG" = true ] && openshift-install create install-config --dir=$DIR_NAME

